{{- if ( .Values.android.apikey ) }}
apiVersion: v1
kind: Secret
metadata:
  name: "android-{{ .Chart.Name }}"
  labels:
    {{- include "gorush.labels" . | nindent 4 }}
type: Opaque
data:
  GORUSH_ANDROID_APIKEY: {{ default "" .Values.android.apikey | stringData | quote }}
{{- end }}
