apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
data:
  config.yaml: |
    {{ with .Values.core }}
    core:
      enabled: {{ .enabled }} 
      address: {{ .address }} 
      shutdown_timeout: {{ .shutdown_timeout }} 
      port: {{ .port }} 
      worker_num: {{ .worker_num }} 
      queue_num: {{ .queue_num }} 
      max_notification: {{ .max_notification }}
      sync: {{ .sync }} 
      feedback_hook_url: {{ .feedback_hook_url }} 
      feedback_timeout: {{ .feedback_timeout }} 
      mode: {{ .mode }}
      ssl: {{ .ssl }}
      cert_path: {{ .cert_path }}
      key_path: {{ .key_path }}
      http_proxy: {{ .http_proxy }}
      {{ with .pid }}
      pid:
        enabled: {{ .enabled }}
        path: {{ .path }}
        override: {{ .override }}
      {{ end }}
      {{ with .auto_tls }}
      auto_tls:
        enabled: {{ .enabled }} 
        folder: {{ .folder }} 
        host: {{ .host }} 
      {{ end }}
    {{ end }}
    {{ with .Values.grpc }}
    grpc:
      enabled: {{ .enabled }} 
      port: {{ .port }}
    {{ end }}
    {{ with .Values.api }}
    api:
      push_uri: {{ .push_uri }}
      stat_go_uri: {{ .stat_go_uri }}
      stat_app_uri: {{ .stat_app_uri }}
      config_uri: {{ .config_uri }}
      sys_stat_uri: {{ .sys_stat_uri }}
      metric_uri: {{ .metric_uri }}
      health_uri: {{ .health_uri }}
    {{ end }}
    {{ with .Values.android }}
    android:
      enabled: {{ .enabled }}
      max_retry: {{ .max_retry }} 
    {{ end }}
    {{ with .Values.huawei }}
    huawei:
      enabled: {{ .enabled }}
      appsecret: {{ .appsecret }}
      appid: {{ .appid }}
      max_retry: {{ .max_retry }} 
    {{ end }}
    {{ with .Values.queue }}
    queue:
      engine: {{ .engine }} 
      {{ with .nsq }}
      nsq:
        addr: {{ .addr }}
        topic: {{ .topic }}
        channel: {{ .channel }}
      {{ end }}
      {{ with .nats }}
      nats:
        addr: {{ .addr }}
        subj: {{ .subj }}
        queue: {{ .queue }}
      {{ end }}
    {{ end }}
    {{ with .Values.ios }}
    ios:
      enabled: {{ .enabled }}
      key_path: {{ .key_path }}
      key_type: {{ .key_type }}
      production: {{ .production }}
      max_concurrent_pushes: {{ .max_concurrent_pushes }} 
      max_retry: {{ .max_retry }} 
      key_id: {{ .key_id }} 
      team_id: {{ .team_id }} 
    {{ end }}
    {{ with .Values.log }}
    log:
      format: {{ .format }} 
      access_log: {{ .access_log }} 
      access_level: {{ .access_level }}
      error_log: {{ .error_log }} 
      error_level: {{ .error_level }}
      hide_token: {{ .hide_token }}
    {{ end }}
    stat:
      engine: {{ .Values.stat.engine }}
      {{- if eq .Values.stat.engine "redis" }}
      redis:
        {{- if .Values.redis.enabled }}
        addr: {{ printf "%s-master" (include "common.names.fullname" .) }}
        {{- else }}
        addr: {{ .Values.redis.externalAddress }}
        {{- end }}
        db: {{ .Values.redis.global.redis.password }}
      {{- else if eq .Values.stat.engine "boltdb" }}
      boltdb:
        path: {{ .Values.stat.boltdb.path }}
        bucket: {{ .Values.stat.boltdb.bucket }}
      {{- else if eq .Values.stat.engine "buntdb" }}
      buntdb:
        path: {{ .Values.stat.buntdb.path }}
      {{- else if eq .Values.stat.engine "leveldb" }}
      leveldb:
        path: {{ .Values.stat.leveldb.path }}
      {{- else if eq .Values.stat.engine "badgerdb" }}
      badgerdb:
        path: {{ .Values.stat.badgerdb.path }}
      {{- end }}
