apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gorush.labels" . | nindent 4 }}
type: Opaque
data:
  android-push-credentials: {{ default "" .Values.android.apikey | b64enc | quote }}
  huawei-push-credentials: {{ default "" .Values.huawei.appsecret | b64enc | quote }}
