{{- if ( .Values.stat.redis.password ) }}
apiVersion: v1
kind: Secret
metadata:
  name: "stat-{{ .Chart.Name }}"
  labels:
    {{- include "gorush.labels" . | nindent 4 }}
type: Opaque
stringData:
  GORUSH_STAT_REDIS_PASSWORD: {{ default "" .Values.stat.redis.password | quote }}
{{- end }}
